### ISSUE TITLE
inventory-helidon missing inventory-service.yaml

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#107]
inventory-helidon/deploy.sh refers to inventory-service.yaml but that file does not exist.  As a result, the service does not get created and inventory-helidon/undeploy.sh fails which breaks the auto test.

**Comment by RichardExley** [comment]
I am going to comment out these lines for now so that the auto test works.

**Comment by paulparkinson** [comment]
thanks for this. I will add inventory-service.yaml as the plan is to provide rest endpoints on inventory service
