### ISSUE TITLE
polyglot tests failure

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#108]
First order is left in pending state and breaks auto test.  Repros on Live Labs and Free Trial.  Second message is processed.

`TEST_LOG_FAILED: Polyglot inventory-dotnet showOrder 366 nomatch`

`Result

{
  "orderid": "366",
  "itemid": "sushi",
  "deliverylocation": "780 PANORAMA DR, San francisco, CA",
  "status": "pending",
  "inventoryLocation": "",
  "suggestiveSale": ""
}`

**Comment by paulparkinson** [comment]
looking at it now...

**Comment by paulparkinson** [comment]
just noting the polyglot-test.sh list here and the order of the impls run. 
inventory-dotnet test that fails comes after inventory-python and inventory-nodejs.

SERVICES="inventory-python inventory-nodejs inventory-dotnet inventory-go inventory-helidon-se"

**Comment by paulparkinson** [comment]
Just want to confirm, is this consistent or intermittent and how you are running/reproducing the issue so that I can do the same? Thanks.

**Comment by RichardExley** [comment]
It reproduced on both free trial and live labs and so I assumed it was reproducible.

**Comment by paulparkinson** [comment]
When I run auto test (`source test.sh`) it passes this test: "TEST_LOG: Polyglot inventory-dotnet placeOrder 366 succeeded"
Unless I've accidentally fixed something in my tx :) but then I've never hit this error running auto test. 
I think you had a 100% auto test before as well. Are you saying this is a regression from then or do I have the reproducer wrong?

**Comment by RichardExley** [comment]
This may have been masked by the password issue.  I repro'd again today.

**Comment by RichardExley** [comment]
And repro'd again just now.  Free trial account running the auto test.  order 366 never gets out of status pending.  Could be the order message never gets sent I suppose.  Or could be something with the ordering of tests perhaps?

**Comment by RichardExley** [comment]
To investigate further I switch dotnet with go in the running order and no the inventory-go service has the issue.  Could it be the nodejs service is pulling the order message off the queue before it terminates?

**Comment by paulparkinson** [comment]
yes, I was wondering exactly that since I had fixed the original issue re dotnet and go that exhibited the same behavior a while back.  I was wondering if we can add an assert that previous deployments/pods are down before starting the next text?

**Comment by RichardExley** [comment]
I commented out this line in the app.js file and the problem goes away:

`  oracledb.autoCommit = false;`

This change was made as part of #41 on May 12.  

I don't regard this as a fix because I don't know why this changes the behavior in the way it does.  I would have thought that we would not want auto commit.  Needs further investigation.

**Comment by RichardExley** [comment]
I think it is a good idea to check that one inventory service is down before starting another.  I will raise an issue for that.  We also need to get to the bottom of why inventory-nodejs is breaking "all or nothing".

**Comment by RichardExley** [comment]
#113

**Comment by paulparkinson** [comment]
agreed

**Comment by paulparkinson** [comment]
This does not seem related to inventory-dotnet failure (as other tests fail depending on the scenario/order) and the autocommit setting in app.js seems to have no bearing thus changing the title of the issue.  I'm still not sure what is happening here but it seems likely related to the test setup somehow as some runs are successful and individual testing of the polyglot tests passes.

**Comment by paulparkinson** [comment]
I made a number of changes in this area and I believe this is fixed. Have run it many times with success. We can reopen if we see it again of course.
