### ISSUE TITLE
separate `utils` dir for user and build, re-enable msdataworkshop to display all user commands

### ISSUE THREAD

**Issue by paulparkinson** [oracle/microservices-datadriven#111]
Currently both build and workshop user utils are in the same directory.

This should be separated to be more organized in general but it also appears the `ls utils` command was removed from the end of the `msdataworkshop` command at some point.

The `msdataworkshop` command is meant to be a goto help command that shows all possible utility and short cut commands (useful for debugging and developing/understanding) and thus anything that is under utils dir.  

We can do this a few different ways but the simplest is to revert back to having the `ls utils` at the end of the `msdataworkshop` command as mentioned which is dynamic when new commands are added. Regardless the directory should be for user scripts/utils only.

**Comment by RichardExley** [comment]
My reorg is going to change a lot of this so we should coordinate

**Comment by paulparkinson** [comment]
sounds good - probably I can move all the util commands (from their current home in individual file and env.sh) into a utils.sh file and we can just source that whereever it may land.

**Comment by paulparkinson** [comment]
Assigning this to you @RichardExley if you don't mind. Definitely feel free to assign it to me if your re-org doesn't cover this of course. Thanks.
