### ISSUE TITLE
separate sql file from setup-db.sh

### ISSUE THREAD

**Issue by paulparkinson** [oracle/microservices-datadriven#137]
to decouple it, make it easy to refer to from blogs, etc. and as re-usable as possible

**Comment by RichardExley** [comment]
I agree with the motivation, but there are some challenges.  
1) Variable substitution is used to parameterize the SQL
2) The DB password is passed via parameter substitution in order to avoid passing it in the sqlplus command line.  We would want to avoid saving a file with the password embedded.

**Comment by paulparkinson** [comment]
Right, I think we could still leave in the param substitution and keep the connect logic outside the sql file (ie still in the db-setup.sh)
