### ISSUE TITLE
FAN should be turned off when connecting to ATP

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#225]
ATP on shared infra does not support FAN.  We need to have a mechanism to turn off FAN in our microservices when connecting to ATP-S.  In the Python and NodeJS inventory microservices the time to instantiate the connection pool was dramatically reduced once FAN was disabled (15 seconds ro 1 second).  Here is the current message from the order-helidon service:

```
Oct 06, 2021 11:35:35 PM oracle.simplefan.impl.FanManager configure
SEVERE: attempt to configure ONS in FanManager failed with oracle.ons.NoServersAvailable: Subscription time out
```

**Comment by RichardExley** [comment]
There appears to be a bug in latest UCP on this.  Need to log bug.

**Comment by paulparkinson** [comment]
there is one. current workaround is apparently to use JDBC/UCP 21c with 19c ONS. will wait for official fix I think
