### ISSUE TITLE
Update "####FAILURE####" logs message for test.sh

### ISSUE THREAD

**Issue by matayal** [oracle/microservices-datadriven#229]
Update test.sh for log details "#### FAILURES ####" to "FAILURE RESULTS" or "Failure: 0/ No Failure exits"

**Comment by karthiparani** [comment]
Hi Mayank,

Could you please recheck whether the bug is fixed or not?

Best Regards,
Karthika

**Comment by matayal** [comment]
> Hi Mayank,
> 
> Could you please recheck whether the bug is fixed or not?
> 
> Best Regards, Karthika

Hi Karthika,

However, this bug is not related to any functionality. It's just a manual change in the text/representation. I'll update once it delivers. 

Thanks,
Mayank Tayal

**Comment by karthiparani** [comment]
Hi Mayank,

Thanks for the update.

Best Regards,
Karthika
