### ISSUE TITLE
foodwinepairing-python build is failing

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#271]
Here is the error:

```
Nightly Builds
==============

For nightly builds, see ppa:deadsnakes/nightly https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly
 More info: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
Error: retrieving gpg key timed out.
The command '/bin/sh -c add-apt-repository ppa:deadsnakes/ppa' returned a non-zero code: 1

```

**Comment by RichardExley** [comment]
This happened in my South Korean free trial tenancy.  I reran the build and it failed the same way a second time.

**Comment by paulparkinson** [comment]
Yes, I think it is intermittent in that it's related to resources and has a better chance when it's run by itself (ie not in parallel build during setup) - fixing #251 (ie optimizing dockerfile) should hopefully address this.
