### ISSUE TITLE
Deploy functions could be more intuitive

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#329]
It took me a few minutes to actually find the generated yaml as the deploy.sh refers the user to # See docs/Deploy.md for details which at the end of the doc in turn refers the user to See common/docs/DeployFunctions.md for details.  which halfway down the page states The processed yaml files are place in the .deployed folder in the home directory of the microservice.  I don’t think this is very intuitive for the customer and at the very least we should change the folder to generated_yaml or some such and the fact that the folder is named with a . prefix makes it hidden as far as ls command (requires ls -al).

**Comment by RichardExley** [comment]
If we change the name of the folder we must also change the .gitignore to make sure the generated yaml don't get checked in.

**Comment by paulparkinson** [comment]
files don't get committed unless they are explicitly `git added` so should not be an issue
