### ISSUE TITLE
issues with observability workshop

### ISSUE THREAD

**Issue by paulparkinson** [oracle/microservices-datadriven#354]
http://bit.ly/unifiedobservability

**Comment by markxnelson** [comment]
lab 3 - task 1 - saw these warnings - might be a good idea to fix these soon, not sure when oke are going up to 1.22, but 1.23 is out already and i think 1.22 EOL's in a few months

```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/prometheus created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/prometheus created
```

**Comment by markxnelson** [comment]
lab 3 task 1 - typo in second command
```
markxnelso@cloudshell:observability (us-phoenix-1)$ cd $GRABDISH_HOME/observability;./createMonitorsAndExporters.sh
bash: ./createMonitorsAndExporters.sh: No such file or directory
markxnelso@cloudshell:observability (us-phoenix-1)$ ls
createMonitorsAndDBAndLogExporters.sh  dashboards  db-log-exporter  db-metrics-exporter  install  install.sh  README.md  updatedbteqexporters.sh
markxnelso@cloudshell:observability (us-phoenix-1)$ 
```

**Comment by markxnelson** [comment]
in lab 4 task 2 at the end of step 1 it says to go to notification settings and select "default" but that option does not seem to exist

**Comment by markxnelson** [comment]
in fact, in lab 4 - most of the grafana screens look quite different, i think the lab was written against an older version than what it is picking up now

**Comment by markxnelson** [comment]
lab6, task3 - missing the `./` before `test40usersFor5Minutes.sh`

**Comment by markxnelson** [comment]
in lab7, task 1
i think there is a typo

Modify and save
$GRABDISH_HOME/observability/db-metrics-exporter/db-metrics-inventorypdb-exporter-metrics.toml and/or $GRABDISH_HOME/observability/db-metrics-exporter/db-metrics-inventorypdb-exporter-metrics.toml and run the following command.

one of those should be orderpdb i am guessing
