### ISSUE TITLE
TEQ in Oracle Database: ER: Prepare the workshop to rerun

### ISSUE THREAD

**Issue by pasimoes** [oracle/microservices-datadriven#359]
Enhancement Request for [Simplify Event-driven Apps with TEQ in Oracle Database (with Kafka interoperability) Workshop](http://bit.ly/TEQinOracleDatabase) (W8022)

Issuer: Kevin Zhang :+1:

Details: 
When I tried to rerun the Lab4: interoperability between Kafka and TEQ, I found the config JSON changed. I suggest you make a copy of the original file and then overwrite the temporary file with a password or something like that.

**Comment by karthiparani** [comment]
Greetings!

Please rerun in Dev environment and confirm.

Regards,
Karthika
