### ISSUE TITLE
Lab 1 : Collection of SQLs from the Applications using SQL Tuning Sets

### ISSUE THREAD

**Issue by praveennhiremath** [oracle/microservices-datadriven#377]
The Application generates the logs the as and when the user access it. We have something called SQL Tuning sets which actually captures the workload  generated by the application on DB. The workload is nothing but the SQL statements executed by the system. These SQL tuning sets executed periodically and collects the statistics from the cursor cache which basically captures the metadata of the workload. The metadata like Table names is stored in the pipeline DB.

**Comment by markxnelson** [comment]
https://github.com/markxnelson/learning-library/blob/master/developer-library/microservices-data-refactoring/collect-usage/collect-usage.md
