### ISSUE TITLE
DCMS-OCI Setup May Exceed Docker Pull Limits

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#397]
Docker has imposed a limit of 100 pulls per 6 hours for anon users.  We hit this when multiple users were simultaneously running in Live Labs.  We assume this is because their cloud shells were running on a common server and therefore sharing the same IP address (from Docker's perspective) and therefore appeared to be the same anonymous user.

**Comment by andytael** [comment]
Changed and tested using a new repo for OL
