### ISSUE TITLE
Failing foodwinepairing-python Build

### ISSUE THREAD

**Issue by RichardExley** [oracle/microservices-datadriven#399]
The build is failing.  This is new this week.  I tested in my tenancy and live labs with the same result.  

`    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -c gensim/models/word2vec_inner.c -o build/temp.linux-x86_64-3.6/gensim/models/word2vec_inner.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u2nqawvq/gensim_c5bfe9f77a36423facd43391a943e437/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u2nqawvq/gensim_c5bfe9f77a36423facd43391a943e437/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lcr_qb8l/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/gensim Check the logs for full command output.
T`

**Comment by RichardExley** [comment]
[build_foodwinepairing-python.log](https://github.com/oracle/microservices-datadriven/files/8605784/build_foodwinepairing-python.log)

**Comment by andytael** [comment]
Adding `yum install gcc` changes to Dockerfile the error to
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -c gensim/models/word2vec_inner.c -o build/temp.linux-x86_64-3.6/gensim/models/word2vec_inner.o
    gensim/models/word2vec_inner.c:25:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
