### ISSUE TITLE
Change shortening of TEQ to TxEventQ WSM 8022

### ISSUE THREAD

**Issue by andytael** [oracle/microservices-datadriven#475]
Instead of shortening Transactional Event Queues to TEQ, we'll be using TxEventQ. This was decided by Juan last week.

This will include:
- [x] Lab Tasks Text
- [x] Lab Tasks Pictures
- [x] Lab Tasks Outputs
- [x] Shell scripts
- [x] Java Code
- [x] SQL Scripts
- [x] WSM Tool needs updates to titles and descriptions

**Comment by pasimoes** [comment]
Official Docs should be updated
https://docs.oracle.com/en/database/oracle/oracle-database/21/adque/Kafka_cient_interface_TEQ.html#GUID-94589C97-F323-4607-8C3A-10A0EDF9DA0D
