### ISSUE TITLE
OBaaS - Prereq - OKE should have three nodes at least because resources for APISIX.

### ISSUE THREAD

**Issue by pasimoes** [oracle/microservices-datadriven#524]
APISIX is not available under 3 nodes for CPU resources limit. We have to investigate this limit.

**Comment by andytael** [comment]
@pasimoes How did you determine this problem?

**Comment by pasimoes** [comment]
When creating the environment using the template and choosing one node (OKE), the APISIX doesn't work because it is missing resources.
