### ISSUE TITLE
AQ/TEQ Workshop broken

### ISSUE THREAD

**Issue by AmedeeBulle** [oracle/microservices-datadriven#613]
Hi, 

There are a couple of issues with this workshop...

The setup script does a `cd aqJava`, but that directory has apparently been renamed to `qJava`
https://github.com/oracle/microservices-datadriven/blob/d0acef13f5151d60a692b32805e7d30a7806b2ce/workshops/oracleAQ/setup.sh#L219

Also the java app doesn't compile as  `EnqueueDequeueTEQ.java` and `WorkflowTEQ.java` are referring to `constantname.teq_...` variables which aren't defined.
I believe this is linked to d0acef13f5151d60a692b32805e7d30a7806b2ce which renamed `teq` in `TxEventQ` ; it builds fine if I checkout the previous commit (b6461dc) 
It seems to work as well if we rename the constants in these 2 files, but there is also an unfortunate rename in 
https://github.com/oracle/microservices-datadriven/blob/d0acef13f5151d60a692b32805e7d30a7806b2ce/workshops/oracleAQ/qJava/src/main/java/com/examples/config/ConstantName.java#L11
(should be `aq_createQueue`)

**Comment by matayal** [comment]
fixed and deployed.
