### ISSUE TITLE
allow ./build.sh , ./deploy.sh , etc. to work outside ws/cloudshell env

### ISSUE THREAD

**Issue by paulparkinson** [oracle/microservices-datadriven#87]
Would be very nice to allow users to work from local machine rather than cloud shell once the initial workshop setup is complete.

The two main tasks here being...

1. either allow port of cloud shell env (ie instructions to copy "state" folder and source xyz to get state_get on path etc.) or allow local setting/override of DOCKER_REGISTRY etc.

2. get rid of sed usage as it's not OS portable (fails on mac).

**Comment by RichardExley** [comment]
By "very nice", I assume the primary benefit would be to facilitate tight development with IDE, git, etc?  I believe this is not possible with cloud shell due to network constraints?  Would this be primarily for our internal development or also for external use?

Presumably we would also need to install docker, oci, kubectl, etc.  And decide which platforms we want to support and test on each.

**Comment by paulparkinson** [comment]
Right, I think we'd limit it to cloud shell as far as official support but that we should have a path to its basic usage outside the workshop.  As you say IDE etc. dev is not possible using the cloud shell alone and I think the two items I mention (and insuring docker login is successful) are enough. We can state/doc the docker, oci, kubectl, and mvn versions used in the workshop and leave it at that I think.

**Comment by paulparkinson** [comment]
ideally both setting/override of .kube/config and DOCKER_REGISTRY should be possible  so we can run against non OCI k8s and container registries.

**Comment by RichardExley** [comment]
The support for dev on Mac is implemented and documented here - https://github.com/oracle/microservices-datadriven/blob/main/grabdish/docs/LocalDev.md.

**Comment by RichardExley** [comment]
Re "ideally both setting/override of .kube/config and DOCKER_REGISTRY should be possible so we can run against non OCI k8s and container registries.", the implementation does not require specific Kubeconfig, but all the other setup steps would be required before a k8s would be able to run our services.  What did you have in mind for DOCKER_REGISTRY?  What is the use case?

**Comment by paulparkinson** [comment]
Just trying to make it as decoupled as possible so that a user could conceivably come in (from a blog link eg) and build and deploy just one module/service.  Of course they would need to account for db setup, etc. but as close to that mark as possible would be the idea.

So I was wondering if we could 
1. Allow the user to specify DOCKER_REGISTRY (and any others) in env and only if it does not exist then call state_get
2. Use the sed command directly rather than call sed_i function

The above two items would decouple the individual modules/services and the workshop infra.

**Comment by paulparkinson** [comment]
As discussed...
I’ve made the following changes in 
build.sh (https://github.com/paulparkinson/microservices-datadriven/blob/main/grabdish/order-helidon/build.sh) 
and 
deploy.sh (https://github.com/paulparkinson/microservices-datadriven/blob/main/grabdish/order-helidon/deploy.sh) 
in my fork to
1. use env values if they exist (if not use state_get) and
2. use longhand sed -e to avoid using sed_i
that will be adopted for this endeavor.

**Comment by paulparkinson** [comment]
this is done for all of the "core" microservices via #196 , however, leaving it open as the same just needs to be done for the polyglot inventory impls
